### ISSUE TITLE
Client is expecting us to have a different public key

### ISSUE THREAD

**Issue by cryptoklings** [aptos-labs/aptos-ait1#3]
A misunderstanding when registering my node, I assume I registered the keys from `validator-identity.yaml` without realizing that these were identical to those in `private-keys.yaml`.

The error message is self-explanatory. If there is any chance that I can generate new keys and join the network in a later update, I would certainly be thrilled do that. 

May 24 20:49:41 appsec-cryptonode-aptos aptos[10743]: testnet-validator-1  | 2022-05-24T20:49:41.231136Z [network-Validator] WARN network/src/peer_manager/transport.rs:309 [validator,Validator,80299b2b] Inbound connection from /ip4/43.156.128.254/tcp/54748 failed to upgrade after 0.000 secs: noise server: client 951a0a18: client is expecting us to have a different public key: <`redacted private key>` {"error":"noise server: client 951a0a18: client is expecting us to have a different public key: `<redacted private key>`","network_address":"/ip4/43.156.128.254/tcp/54748","network_context":{"network_id":"Validator","peer_id":"80299b2b633e3d7bcce39b35b752d69fe4a0ca162baab8f630810e9b569e525d","role":"validator"}}

The node is still running, let me know if I should just shut it down to not create noise for the rest of the (healthy) network.

**Comment by cleverelk** [comment]
I am completely in solidarity, I have the same problem and I do not remove Windows from myself.
I will be very grateful to the team if they give me the opportunity to participate
